name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Create appsettings.json from secrets
      run: |
        mkdir -p Portfolyo.WebApi
        echo "{" > Portfolyo.WebApi/appsettings.json
        echo '  "Logging": {"LogLevel": {"Default": "Information","Microsoft.AspNetCore": "Warning"}},' >> Portfolyo.WebApi/appsettings.json
        echo '  "AllowedHosts": "*",' >> Portfolyo.WebApi/appsettings.json
        echo '  "ConnectionStrings": {"SqlServer": "${{ secrets.DB_CONNECTION_STRING }}"},' >> Portfolyo.WebApi/appsettings.json
        echo '  "Jwt": {"Issuer": "${{ secrets.JWT_ISSUER }}","Audience": "${{ secrets.JWT_AUDIENCE }}","SecretKey": "${{ secrets.JWT_SECRETKEY }}"}}' >> Portfolyo.WebApi/appsettings.json
        echo "}" >> Portfolyo.WebApi/appsettings.json

    - name: Restore dependencies
      run: dotnet restore Portfolyo.sln

      
    - name: Build project
      run: dotnet build Portfolyo.sln -c Release --no-restore

    - name: Run unit tests
      run: dotnet publish Portfolyo.sln --no-build --verbosity normal


    - name: Publish project
      run: dotnet publish ./Portfolyo.sln/Portfolyo.WebApi.csproj -c Release -o ./publish --no-build --output './publish'
    - name: Deployment 
      uses: azure/webapps-deploy@v2
      with:
        app-name: YaşarApaydınPortfolyo
        publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
        package: './publish'
       
   
      
