name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Create appsettings.json from secrets
      run: |
        mkdir -p Portfolyo.WebApi
        cat <<EOF > Portfolyo.WebApi/appsettings.json
        {
          "Logging": {
            "LogLevel": {
              "Default": "Information",
              "Microsoft.AspNetCore": "Warning"
            }
          },
          "AllowedHosts": "*",
          "ConnectionStrings": {
            "SqlServer": "${{ secrets.DB_CONNECTION_STRING }}"
          },
          "Jwt": {
            "Issuer": "${{ secrets.JWT_ISSUER }}",
            "Audience": "${{ secrets.JWT_AUDIENCE }}",
            "SecretKey": "${{ secrets.JWT_SECRETKEY }}"
          }
        }
        EOF

    - name: Restore dependencies
      run: dotnet restore Portfolyo.sln

    - name: Build project
      run: dotnet build Portfolyo.sln -c Release --no-restore

    - name: Run unit tests
      run: dotnet test Portfolyo.sln --no-build --verbosity normal

    - name: Publish project
      run: dotnet publish ./Portfolyo.WebApi/Portfolyo.WebApi.csproj -c Release --no-build --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YasarApaydinPortfolyo'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './publish'
